In [1]:
import sys 
sys.path.append('../')
import pandas as pd 
import numpy as np 
import talib
import sqlite3 as sql
import matplotlib.pyplot as plt 
from backtester import * 
from fxcmtoken import my_assets

In [2]:
for i, a in enumerate(my_assets):
    print(i, a)

0 EUR/USD
1 USD/JPY
2 GBP/USD
3 USOil
4 SPX500
5 VOLX
6 XAU/USD
7 Bund
8 BTC/USD

In [20]:
conn = sql.connect('../PriceData/PriceData_m5.db')
ticker = my_assets[8]
print(ticker)
data_sql = pd.read_sql(f"SELECT * FROM '{ticker}'", conn, parse_dates=['date'], index_col=['date'])
for col in ['open', 'close', 'high', 'low']:
    data_sql[col] = data_sql[['bid'+col, 'ask'+col]].mean(axis=1)
conn.close()
data_sql.tail()

BTC/USD

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,open,close,high,low
date,,,,,,,,,,,,,
2022-07-08 20:30:00,21909.0,21933.2,21963.0,21865.0,21949.0,21973.2,22003.0,21905.0,571,21929.0,21953.2,21983.0,21885.0
2022-07-08 20:35:00,21932.8,21839.1,21993.9,21825.6,21972.8,21879.1,22033.9,21865.6,777,21952.8,21859.1,22013.9,21845.6
2022-07-08 20:40:00,21839.5,21859.5,21877.0,21788.4,21879.5,21899.5,21917.0,21828.4,584,21859.5,21879.5,21897.0,21808.4
2022-07-08 20:45:00,21860.6,21827.1,21860.6,21791.2,21900.6,21867.1,21900.6,21831.2,539,21880.6,21847.1,21880.6,21811.2
2022-07-08 20:50:00,21825.3,21843.6,21844.8,21798.7,21865.3,21863.6,21884.8,21838.7,408,21845.3,21853.6,21864.8,21818.7

In [21]:
num_periods =  [i for i in range(50, 501, 50)]

for n_period in num_periods:
    data = data_sql.copy(deep=True)
    print(ticker)
    print(f"Period: {n_period}")

    data['slope_bin'] = talib.LINEARREG_SLOPE(data.close, timeperiod=n_period).apply(np.sign)

#     data[['close', 'slope_bin']].plot(figsize=(12,6), secondary_y='slope_bin')
#     plt.tight_layout()
#     plt.show()

    data.dropna(axis=0, inplace=True)

    backtest = IterativeBacktester(data=data,
                                   signals=data.slope_bin,
                                   freq='m5')

    backtest.backtest(progress_bar=False)
    # backtest.results()
    print(f"{backtest.return_df.loc['TotalReturn', 'Portfolio']*100:.4f}%")
    
    print("Signals")
    print(backtest.signals.value_counts())

    print("Signals change")
    print(backtest.signals.diff(1).dropna().apply(np.abs).value_counts())
    
    print("-"*50)

BTC/USD
Period: 50
17.3772%
Signals
-1.0    5129
 1.0    4822
Name: slope_bin, dtype: int64
Signals change
0.0    9736
2.0     214
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 100
2.5316%
Signals
-1.0    5218
 1.0    4683
Name: slope_bin, dtype: int64
Signals change
0.0    9796
2.0     104
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 150
2.3637%
Signals
-1.0    5179
 1.0    4672
Name: slope_bin, dtype: int64
Signals change
0.0    9780
2.0      70
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 200
-6.0862%
Signals
-1.0    5253
 1.0    4548
Name: slope_bin, dtype: int64
Signals change
0.0    9749
2.0      51
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 250
-28.1034%
Signals
-1.0    5211
 1.0    4540
Name: slope_bin, dtype: int64
Signals change
0.0    9706
2.0      44
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 300
-18.8218%
Signals
-1.0    5347
 1.0    4354
Name: slope_bin, dtype: int64
Signals change
0.0    9660
2.0      40
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 350
2.8615%
Signals
-1.0    5473
 1.0    4178
Name: slope_bin, dtype: int64
Signals change
0.0    9627
2.0      23
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 400
-7.6203%
Signals
-1.0    5387
 1.0    4214
Name: slope_bin, dtype: int64
Signals change
0.0    9577
2.0      23
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 450
-3.5981%
Signals
-1.0    5313
 1.0    4238
Name: slope_bin, dtype: int64
Signals change
0.0    9527
2.0      23
Name: slope_bin, dtype: int64
--------------------------------------------------
BTC/USD
Period: 500
2.7738%
Signals
-1.0    5351
 1.0    4150
Name: slope_bin, dtype: int64
Signals change
0.0    9481
2.0      19
Name: slope_bin, dtype: int64
--------------------------------------------------