In [1]:
import sys
sys.path.append('../')
import sqlite3
import json
from backtester import *
from fxcmtoken import major_forex_pairs
from sklearn.model_selection import train_test_split
from datetime import datetime

In [2]:
major_forex_pairs

['EUR/USD', 'GBP/USD', 'USD/JPY', 'USD/CHF', 'USD/CAD', 'AUD/USD', 'NZD/USD']

In [4]:
freq = 'm15'
conn = sqlite3.connect(f'../PriceData/PriceData_{freq}.db')
ticker = major_forex_pairs[0]
print(ticker)
data = pd.read_sql(f"SELECT * FROM '{ticker}'", conn, parse_dates=['date'], index_col=['date'])
conn.close()
columns = ['open', 'high', 'low', 'close']
for col in columns:
    data[col] = data[['bid'+col, 'ask'+col]].mean(axis=1)
# display(data.head())
# display(data.tail())
print(data.shape)
# display(data)
# test_size = 0.048 # m15
test_size = 0.1455
# test_size = 0.144 # m5
test_len = int(test_size * len(data))
print("test length", test_len)
# train_data, test_data = train_test_split(data, test_size=test_size, shuffle=False)
# data = train_data
# data = test_data
# print(data.shape)
display(data)

EUR/USD
(10000, 13)
test length 1455

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,open,high,low,close
date,,,,,,,,,,,,,
2021-08-03 21:15:00,1.18600,1.18602,1.18609,1.18589,1.18644,1.18644,1.18648,1.18639,39,1.186220,1.186285,1.186140,1.186230
2021-08-03 21:30:00,1.18602,1.18613,1.18613,1.18602,1.18644,1.18651,1.18651,1.18641,86,1.186230,1.186320,1.186215,1.186320
2021-08-03 21:45:00,1.18613,1.18621,1.18623,1.18607,1.18651,1.18648,1.18651,1.18635,116,1.186320,1.186370,1.186210,1.186345
2021-08-03 22:00:00,1.18621,1.18632,1.18638,1.18617,1.18648,1.18646,1.18651,1.18636,262,1.186345,1.186445,1.186265,1.186390
2021-08-03 22:15:00,1.18632,1.18647,1.18653,1.18631,1.18646,1.18661,1.18666,1.18645,632,1.186390,1.186595,1.186380,1.186540
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-24 17:00:00,1.13112,1.13090,1.13135,1.13073,1.13131,1.13126,1.13145,1.13101,4825,1.131215,1.131400,1.130870,1.131080
2021-12-24 17:15:00,1.13092,1.13106,1.13131,1.13074,1.13127,1.13138,1.13170,1.13097,3389,1.131095,1.131505,1.130855,1.131220
2021-12-24 17:30:00,1.13106,1.13094,1.13108,1.13085,1.13137,1.13132,1.13143,1.13114,1348,1.131215,1.131255,1.130995,1.131130
2021-12-24 17:45:00,1.13093,1.13139,1.13148,1.13085,1.13132,1.13189,1.13195,1.13115,829,1.131125,1.131715,1.131000,1.131640
2021-12-24 18:00:00,1.13140,1.13144,1.13154,1.13134,1.13189,1.13180,1.13210,1.13167,1217,1.131645,1.131820,1.131505,1.131620

In [8]:
data.loc["2021-10-24 22:00:00": ]

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,open,high,low,close
date,,,,,,,,,,,,,
2021-12-08 22:33:00,1.13418,1.13419,1.13419,1.13415,1.13442,1.13433,1.13442,1.13432,42,1.134300,1.134305,1.134235,1.134260
2021-12-08 22:34:00,1.13419,1.13422,1.13423,1.13415,1.13433,1.13441,1.13441,1.13432,29,1.134260,1.134320,1.134235,1.134315
2021-12-08 22:35:00,1.13422,1.13424,1.13424,1.13420,1.13441,1.13434,1.13447,1.13434,17,1.134315,1.134355,1.134270,1.134290
2021-12-08 22:36:00,1.13424,1.13416,1.13424,1.13415,1.13434,1.13432,1.13447,1.13431,31,1.134290,1.134355,1.134230,1.134240
2021-12-08 22:37:00,1.13416,1.13414,1.13416,1.13411,1.13432,1.13429,1.13430,1.13428,143,1.134240,1.134230,1.134195,1.134215
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-17 21:55:00,1.12368,1.12357,1.12368,1.12347,1.12389,1.12377,1.12389,1.12368,87,1.123785,1.123785,1.123575,1.123670
2021-12-17 21:56:00,1.12357,1.12345,1.12357,1.12345,1.12375,1.12366,1.12380,1.12364,50,1.123660,1.123685,1.123545,1.123555
2021-12-17 21:57:00,1.12345,1.12350,1.12352,1.12344,1.12365,1.12370,1.12373,1.12365,270,1.123550,1.123625,1.123545,1.123600
2021-12-17 21:58:00,1.12349,1.12354,1.12356,1.12349,1.12370,1.12379,1.12379,1.12370,42,1.123595,1.123675,1.123595,1.123665
2021-12-17 21:59:00,1.12352,1.12355,1.12355,1.12352,1.12376,1.12380,1.12380,1.12376,3,1.123640,1.123675,1.123640,1.123675

In [141]:
data.loc["2021-10-24 22:00:00":"2021-10-29"]

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,open,high,low,close
date,,,,,,,,,,,,,
2021-10-24 22:00:00,1.16365,1.16416,1.16439,1.16355,1.16404,1.16431,1.16460,1.16404,586,1.163845,1.164495,1.163795,1.164235
2021-10-24 22:15:00,1.16416,1.16401,1.16418,1.16400,1.16431,1.16415,1.16433,1.16415,464,1.164235,1.164255,1.164075,1.164080
2021-10-24 22:30:00,1.16401,1.16424,1.16432,1.16399,1.16415,1.16438,1.16445,1.16414,339,1.164080,1.164385,1.164065,1.164310
2021-10-24 22:45:00,1.16424,1.16439,1.16445,1.16416,1.16438,1.16453,1.16459,1.16429,396,1.164310,1.164520,1.164225,1.164460
2021-10-24 23:00:00,1.16439,1.16411,1.16441,1.16408,1.16453,1.16422,1.16454,1.16420,634,1.164460,1.164475,1.164140,1.164165
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-29 19:45:00,1.15561,1.15588,1.15597,1.15561,1.15574,1.15600,1.15609,1.15574,1694,1.155675,1.156030,1.155675,1.155940
2021-10-29 20:00:00,1.15588,1.15609,1.15624,1.15580,1.15600,1.15622,1.15637,1.15592,798,1.155940,1.156305,1.155860,1.156155
2021-10-29 20:15:00,1.15609,1.15611,1.15612,1.15595,1.15622,1.15622,1.15624,1.15608,350,1.156155,1.156180,1.156015,1.156165
2021-10-29 20:30:00,1.15611,1.15569,1.15610,1.15565,1.15622,1.15581,1.15623,1.15580,495,1.156165,1.156165,1.155725,1.155750
2021-10-29 20:45:00,1.15569,1.15605,1.15642,1.15556,1.15581,1.15630,1.15668,1.15570,1311,1.155750,1.156550,1.155630,1.156175

In [38]:
with open(f'../ta_optimize/json/OPTIMIZE_params_{freq}_200_20.json', 'r') as f:
    parameters = json.load(f)
# parameters

In [39]:
for k, v in parameters.items():
    print(k, v[ticker])

EMA [20, 60]
KAMA [20, 60]
MIDPOINT [20, 140]
MIDPRICE [40, 140]
SMA [20, 60]
TRIMA [40, 80]
WMA [60, 80]

In [40]:
indicators = {'SMA' : talib.SMA, 
            'EMA' : talib.EMA, 
#             'DEMA' : talib.DEMA, 
            'KAMA' : talib.KAMA, 
            'MIDPOINT' : talib.MIDPOINT, 
            'MIDPRICE' : talib.MIDPRICE, 
#             'TEMA' : talib.TEMA, 
            'TRIMA' : talib.TRIMA, 
            'WMA' : talib.WMA,
#             'LINREG' : talib.LINEARREG,
#             'TSF' : talib.TSF
             }

for name, func in indicators.items():
    params = parameters[name][ticker]
    for i in range(2):
        d0 = datetime.now()
        if name == 'MIDPRICE':
            data[f"{name}_{i+1}"] = func(data['high'], data['low'], params[i])
        else:
            data[f"{name}_{i+1}"] = func(data['close'], params[i])
        print(f"{name} : {datetime.now() - d0}")

SMA : 0:00:00.001503
SMA : 0:00:00.001253
EMA : 0:00:00.001699
EMA : 0:00:00.001072
KAMA : 0:00:00.001223
KAMA : 0:00:00.001257
MIDPOINT : 0:00:00.001750
MIDPOINT : 0:00:00.003171
MIDPRICE : 0:00:00.002547
MIDPRICE : 0:00:00.003437
TRIMA : 0:00:00.001055
TRIMA : 0:00:00.000990
WMA : 0:00:00.001015
WMA : 0:00:00.001061

In [41]:
data.isna().sum().max()

139

In [43]:
if data.shape[0] > test_len:
    data = data.iloc[-test_len:]
else:
    pass

In [44]:
data = data[:'2021-11-26']

In [45]:
data

,bidopen,bidclose,bidhigh,bidlow,askopen,askclose,askhigh,asklow,tickqty,open,...,KAMA_1,KAMA_2,MIDPOINT_1,MIDPOINT_2,MIDPRICE_1,MIDPRICE_2,TRIMA_1,TRIMA_2,WMA_1,WMA_2
date,,,,,,,,,,,,,,,,,,,,,
2021-11-21 22:00:00,1.12857,1.12854,1.12894,1.12806,1.12942,1.12887,1.12945,1.12865,84,1.128995,...,1.128872,1.129324,1.128807,1.131533,1.130130,1.131203,1.129507,1.130362,1.129454,1.129800
2021-11-21 22:15:00,1.12854,1.12853,1.12854,1.12833,1.12887,1.12878,1.12888,1.12862,44,1.128705,...,1.128868,1.129318,1.128807,1.131533,1.130130,1.131203,1.129427,1.130307,1.129423,1.129746
2021-11-21 22:30:00,1.12853,1.12837,1.12860,1.12837,1.12878,1.12860,1.12887,1.12860,101,1.128655,...,1.128862,1.129310,1.128807,1.131533,1.130130,1.131203,1.129351,1.130253,1.129387,1.129689
2021-11-21 22:45:00,1.12837,1.12852,1.12858,1.12836,1.12860,1.12878,1.12888,1.12860,113,1.128485,...,1.128860,1.129308,1.128807,1.131533,1.130130,1.131203,1.129279,1.130201,1.129358,1.129639
2021-11-21 23:00:00,1.12852,1.12795,1.12852,1.12790,1.12878,1.12809,1.12877,1.12805,1246,1.128650,...,1.128835,1.129293,1.128750,1.131533,1.130095,1.131203,1.129209,1.130150,1.129308,1.129576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-26 20:45:00,1.13212,1.13231,1.13231,1.13202,1.13228,1.13248,1.13251,1.13224,340,1.132200,...,1.130078,1.130322,1.130770,1.126535,1.129907,1.126495,1.130130,1.127005,1.129905,1.128850
2021-11-26 21:00:00,1.13231,1.13271,1.13283,1.13200,1.13248,1.13296,1.13305,1.13243,830,1.132395,...,1.130147,1.130496,1.130990,1.126755,1.130173,1.126760,1.130224,1.127167,1.130050,1.128998
2021-11-26 21:15:00,1.13271,1.13255,1.13289,1.13222,1.13296,1.13325,1.13328,1.13281,313,1.132835,...,1.130262,1.130663,1.131023,1.126788,1.130245,1.126832,1.130313,1.127326,1.130191,1.129145
2021-11-26 21:30:00,1.13255,1.13175,1.13314,1.13175,1.13325,1.13274,1.13336,1.13274,163,1.132900,...,1.130329,1.130753,1.131023,1.126788,1.130327,1.126915,1.130400,1.127485,1.130305,1.129272
2021-11-26 21:45:00,1.13175,1.13057,1.13210,1.13057,1.13274,1.13157,1.13299,1.13124,90,1.132245,...,1.130343,1.130767,1.131023,1.126788,1.130327,1.126915,1.130484,1.127641,1.130376,1.129367

In [43]:
data.dropna(axis=0, inplace= True)
signal_col = []
for name in indicators.keys():
    data[f"{name}_signal"] = np.where(data[f"{name}_1"] > data[f"{name}_2"], 1,
                                      np.where(data[f"{name}_1"] < data[f"{name}_2"], -1, np.nan)) #* -1
    # ffill NA --> avoid 2 statistic mode(s)
    data[f"{name}_signal"] = data[f"{name}_signal"].ffill().fillna(0)
    signal_col.append(f"{name}_signal")
signal_col

['SMA_signal',
 'EMA_signal',
 'KAMA_signal',
 'MIDPOINT_signal',
 'MIDPRICE_signal',
 'TRIMA_signal',
 'WMA_signal']

In [44]:
signals = data[signal_col].mode(axis=1)[0] #* -1
signals

date
2021-11-28 23:15:00    1.0
2021-11-28 23:30:00    1.0
2021-11-28 23:45:00    1.0
2021-11-29 00:00:00    1.0
2021-11-29 00:15:00    1.0
                      ...
2021-12-05 19:30:00   -1.0
2021-12-05 19:45:00   -1.0
2021-12-05 21:15:00   -1.0
2021-12-05 21:30:00   -1.0
2021-12-05 21:45:00   -1.0
Name: 0, Length: 480, dtype: float64

In [45]:
print(data.shape)
print(signals.shape)

(480, 34)
(480,)

In [46]:
print('*** Positions ***')
print(signals.value_counts())
print('-'*50)
print('*** Trades ***')
print(signals.diff(1).apply(np.abs).value_counts())

*** Positions ***
-1.0    279
 1.0    201
Name: 0, dtype: int64
--------------------------------------------------
*** Trades ***
0.0    466
2.0     13
Name: 0, dtype: int64

In [ ]:
backtester = IterativeBacktester(data=data, freq=freq, signals=signals)
backtester.backtest(leave=False)
print(f"*** {ticker} ***")
backtester.results()

In [ ]:
for sign in signal_col:
    backtest = IterativeBacktester(data, data[sign], freq)
    backtest.backtest(progress_bar=False)
    # print(sign)
    backtest.portfolio_df[['Portfolio', 'Benchmark']].plot(color=['tab:blue', 'tab:orange'], xlabel='', figsize=(14,5))
    plt.title(sign, fontsize=20)
    plt.hlines(backtest.init_money, xmin=backtest.portfolio_df.index[0], xmax=backtest.portfolio_df.index[-1], color='k', linestyle='--')
    plt.fill_between(x=backtest.portfolio_df.index, y1=backtest.portfolio_df['Portfolio'], y2=backtest.init_money, color='tab:blue', alpha=0.1)
    plt.fill_between(x=backtest.portfolio_df.index, y1=backtest.portfolio_df['Benchmark'], y2=backtest.init_money, color='tab:orange', alpha=0.1)
    plt.text(backtest.portfolio_df.index[-1], backtest.portfolio_df['Portfolio'][-1], f"Portfolio\nReturn({backtest.portfolio_df['PortfolioReturns'].sum()*100:.2f}%)", color="tab:blue", fontsize=15, fontweight="heavy")
    plt.text(backtest.portfolio_df.index[-1], backtest.portfolio_df['Benchmark'][-1], f"Benchmark\nReturn({backtest.portfolio_df['BenchmarkReturns'].sum()*100:.2f}%)", color="tab:orange", fontsize=15, fontweight="heavy")

In [150]:
def forex_backtest():
    major_forex_pairs = ['EUR/USD', 'GBP/USD', 'USD/JPY', 'USD/CHF', 'USD/CAD', 'AUD/USD', 'NZD/USD']
    returns = []
    for pair in tqdm_notebook(major_forex_pairs, leave=False):
        freq = 'm15'
        conn = sqlite3.connect(f'../PriceData/PriceData_{freq}.db')
        ticker = pair
#         print(ticker)
        data = pd.read_sql(f"SELECT * FROM '{ticker}'", conn, parse_dates=['date'], index_col=['date'])
        conn.close()
        columns = ['open', 'high', 'low', 'close']
        for col in columns:
            data[col] = data[['bid'+col, 'ask'+col]].mean(axis=1)
#         print(data.shape)
        test_size = 0.048 # m15
#         test_size = 0.3409
        test_len = int(test_size * len(data))

        with open(f'../ta_optimize/json/OPTIMIZE_params_{freq}_100_20.json', 'r') as f:
            parameters = json.load(f)

        indicators = {'SMA' : talib.SMA, 
                'EMA' : talib.EMA, 
                'KAMA' : talib.KAMA, 
                'MIDPOINT' : talib.MIDPOINT, 
                'MIDPRICE' : talib.MIDPRICE, 
                'TRIMA' : talib.TRIMA, 
                'WMA' : talib.WMA,
                 }

        for name, func in indicators.items():
            params = parameters[name][ticker]
            for i in range(len(params)):
                d0 = datetime.now()
                if name == 'MIDPRICE':
                    data[f"{name}_{i+1}"] = func(data['high'], data['low'], params[i])
                else:
                    data[f"{name}_{i+1}"] = func(data['close'], params[i])
                #print(f"{name} : {datetime.now() - d0}")

        if data.shape[0] > test_len:
            data = data.iloc[-test_len:]
        else:
            pass
        
        ##### Don't forget this! ##### 
#         data = data.loc[:"2021-10-29"]
#         display(data)
#         break 
        data.dropna(axis=0, inplace= True)
        signal_col = []
        for name in indicators.keys():
            data[f"{name}_signal"] = np.where(data[f"{name}_1"] > data[f"{name}_2"], 1,
                                              np.where(data[f"{name}_1"] < data[f"{name}_2"], -1, np.nan))
            # ffill NA --> avoid 2 statistic mode(s)
            data[f"{name}_signal"] = data[f"{name}_signal"].ffill().fillna(0)
            signal_col.append(f"{name}_signal")

        signals = data[signal_col].mode(axis=1)[0] * -1

        backtester = IterativeBacktester(data=data, freq=freq, signals=signals)
        backtester.backtest(leave=False)
        ret = backtester.return_df.loc['TotalReturn', 'Portfolio']
        returns.append(ret)
        print(f"{ret}")
    print("-"*30)
    print(f"{np.mean(returns)*100:.2f}%")

In [151]:
forex_backtest()

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/475 [00:00<?, ?it/s]

0.014149220886039078

  0%|          | 0/478 [00:00<?, ?it/s]

-0.004851140466704032

  0%|          | 0/488 [00:00<?, ?it/s]

-0.002531968884128654

  0%|          | 0/520 [00:00<?, ?it/s]

-0.0029587412170123265

  0%|          | 0/493 [00:00<?, ?it/s]

0.019655023147157193

  0%|          | 0/479 [00:00<?, ?it/s]

0.0028378626322589735

  0%|          | 0/501 [00:00<?, ?it/s]

0.009352616427026093
------------------------------
0.51%